# Cấu hình cho Website 1
server {
    listen 80;
    server_name web1.longhn055.id.vn; 

    # Trang web HTML chính
    location / {
        root /usr/share/nginx/html/site1;
        index index.html;
    }

    # Điều hướng request API tới Node-RED (Reverse Proxy)
    location /api/ {
        proxy_pass http://nodered_app:1880/api/Long;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Cấu hình cho Website 2
server {
    listen 80;
    server_name web2.longhn055.id.vn; 

    location / {
        root /usr/share/nginx/html/site2;
        index index.html index.htm;
    }
    location /api/ {
        proxy_pass http://nodered_app:1880/api/2;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Cấu hình cho AES (Công cụ Mã hóa & Giải mã)
server {
    listen 80;
    server_name aes.longhn055.id.vn;

    location / {
        root /usr/share/nginx/html/site3;
        index index.html;
    }

    # Proxy các Yêu cầu Mã hóa / Giải mã sang Backend Python
    location /api/ {
        proxy_pass http://py_backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
