# Cấu hình cho Website 1
server {
    listen 80;
    server_name web1.longhn055.id.vn;

    location / {
        root /usr/share/nginx/html/site1;
        index index.html index.htm;
    }
}

# Cấu hình cho Website 2
server {
    listen 80;
    server_name web2.longhn055.id.vn; 

    location / {
        root /usr/share/nginx/html/site2;
        index index.html index.htm;
    }
}
