# Cấu hình cho Website 1
server {
    listen 80;
    server_name web1.longhn055.id.vn;

    location / {
        root /usr/share/nginx/html/site1;
        index index.html index.htm;
    }
    location /api/ {
        proxy_pass http://nodered_app:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Cấu hình cho Website 2
server {
    listen 80;
    server_name web2.longhn055.id.vn; 

    location / {
        root /usr/share/nginx/html/site2;
        index index.html index.htm;
    }
    location /api/ {
        proxy_pass http://nodered_app:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
